# Generated by Django 2.1 on 2019-11-12 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文章分類')),
            ],
            options={
                'verbose_name': '文章分類',
                'verbose_name_plural': '文章分類',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=128, verbose_name='文章標題')),
                ('entry_img', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='文章圖片')),
                ('entry_body', models.TextField(verbose_name='文章正文')),
                ('entry_abstract', models.TextField(blank=True, max_length=256, null=True, verbose_name='文章摘要')),
                ('entry_visiting', models.PositiveIntegerField(default=0, verbose_name='觀看次數')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改時間')),
                ('isFeatured', models.BooleanField(default=None, verbose_name='特色文章')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='文章類別')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文章分類')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='文章標籤'),
        ),
    ]
